/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class SafereverbAudioProcessorEditor  : public SAFEAudioProcessorEditor
{
public:
    SafereverbAudioProcessorEditor (SafereverbAudioProcessor* ownerFilter);
    ~SafereverbAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    
private:
    Image backgroundImage;
    
};


#endif  // PLUGINEDITOR_H_INCLUDED
