/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class SafeharmonicsAudioProcessorEditor  : public SAFEAudioProcessorEditor
{
public:
    SafeharmonicsAudioProcessorEditor (SafeharmonicsAudioProcessor* ownerFilter);
    ~SafeharmonicsAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    
    void updateMeters();
    
private:
    TextEditor f0Box, ampBox;
    
    SafeharmonicsAudioProcessor* getProcessor()
    {
        return static_cast <SafeharmonicsAudioProcessor*> (getAudioProcessor());
    }
};


#endif  // PLUGINEDITOR_H_INCLUDED
