/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
SafeharmonicsAudioProcessorEditor::SafeharmonicsAudioProcessorEditor (SafeharmonicsAudioProcessor* ownerFilter)
    : SAFEAudioProcessorEditor (ownerFilter)
{
    // This is where our plugin's editor size is set.
    setSize (400, 300);
    
    addAndMakeVisible (&f0Box);
    f0Box.setBounds (20, 20, 100, 30);
    
    addAndMakeVisible (&ampBox);
    ampBox.setBounds (20, 60, 100, 30);
}

SafeharmonicsAudioProcessorEditor::~SafeharmonicsAudioProcessorEditor()
{
}

//==============================================================================
void SafeharmonicsAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);
}

void SafeharmonicsAudioProcessorEditor::updateMeters()
{
    SafeharmonicsAudioProcessor* ourProcessor = getProcessor();
    
    double f0 = ourProcessor->getFundamental(); 
    f0Box.setText (String (f0));
}