/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class SafedistortionAudioProcessorEditor  : public SAFEAudioProcessorEditor
{
public:
    SafedistortionAudioProcessorEditor (SafedistortionAudioProcessor* ownerFilter);
    ~SafedistortionAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    
    void sliderUpdate (Slider* slider);
    
    void updateDisplay();
    
    void updateUI();
    
private:
    Image backgroundImage;
    
    FunctionGraph display;
    Array <float> displayInputs;
    
    SafedistortionAudioProcessor* getProcessor()
    {
        return static_cast <SafedistortionAudioProcessor*> (getAudioProcessor());
    }
};


#endif  // PLUGINEDITOR_H_INCLUDED
