/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class SafeequaliserAudioProcessorEditor  : public SAFEAudioProcessorEditor,
                                           public FilterGraph::Listener
{
public:
    SafeequaliserAudioProcessorEditor (SafeequaliserAudioProcessor* ownerFilter);
    ~SafeequaliserAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    
    void sliderUpdate (Slider* slider);
    
    void updateUI();
    
    void filterControlChanged (int controlNum);
    
private:
    Image backgroundImage;
    
    FilterGraph display;
    
    SafeequaliserAudioProcessor* getProcessor()
    {
        return static_cast <SafeequaliserAudioProcessor*> (getAudioProcessor());
    }
};


#endif  // PLUGINEDITOR_H_INCLUDED
